services:
  - type: web
    name: myweb
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    region: frankfurt
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mydb
          property: connectionString
      
databases:
  - name: mydb
    databaseName: mydbname
    user: myuser
    plan: free