services:
  - type: web
    name: myweb
    runtime: node
    envVars:
  - key: dbName
    fromDatabase:
      name: dbName
      property: database
      type: pserv
  - key: dbUser
    fromDatabase:
      name: dbUser
      property: user
      type: pserv
  - key: dbPassword
    fromDatabase:
      name: dbPassword
      property: password
      type: pserv
      
databases:
  - name: mydb