services:
  - type: web
    name: myweb
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: dbName
        fromDatabase:
          name: mydbname
          property: database
      - key: dbUser
        fromDatabase:
          name: mydbname
          property: user
      - key: dbPassword
        fromDatabase:
          name: mydbname
          property: password
      - key: hostName
        fromDatabase:
          name: mydbname
          property: host
      
databases:
  - name: mydb
    databaseName: mydbname
    user: myuser
    plan: free